MAKE[0]="make -C linux KVERSION=${kernelver} KDIR=${kernel_source_dir} MODULES='coaxlink grablink gigelink'"
CLEAN="true"

BUILT_MODULE_NAME[0]=coaxlink
BUILT_MODULE_LOCATION[0]=linux/
DEST_MODULE_LOCATION[0]=/kernel

BUILT_MODULE_NAME[1]=grablink
BUILT_MODULE_LOCATION[1]=linux/
DEST_MODULE_LOCATION[1]=/kernel

BUILT_MODULE_NAME[2]=gigelink
BUILT_MODULE_LOCATION[2]=linux/
DEST_MODULE_LOCATION[2]=/kernel

PACKAGE_NAME=egrabber
PACKAGE_VERSION=26.02.1.18
AUTOINSTALL="yes"
