KVERSION ?= $(shell uname -r)
MODULE_LOWERCASE=$(shell echo $(MODULE) | tr '[A-Z]' '[a-z]')

M ?= .
KDIR ?= /lib/modules/$(KVERSION)/build

include $(KDIR)/include/config/auto.conf
include $(KDIR)/scripts/Kbuild.include
include $(KDIR)/scripts/Makefile.lib

ifeq ($(CONFIG_X86_64),y)
HARDENED =
ifeq ($(CONFIG_RETHUNK),y)
HARDENED = _h
else ifeq ($(CONFIG_MITIGATION_RETHUNK),y)
HARDENED = _h
endif
endif

PRECOMP=$(M)/../precompiled/x86_64/mc_$(MODULE_LOWERCASE)_h.o

default: $(PRECOMP).patched

$(PRECOMP).patched: $(PRECOMP)
ifeq ($(HARDENED),_h)
	$(KDIR)/$(objtool) $(objtool-args) $(PRECOMP)
	touch $@
endif
