MAKE[0]="make -C linux KVERSION=${kernelver} KDIR=${kernel_source_dir} MODULES='memento'"
CLEAN="true"

BUILT_MODULE_NAME[0]=memento
BUILT_MODULE_LOCATION[0]=linux/
DEST_MODULE_LOCATION[0]=/kernel

PACKAGE_NAME=memento
PACKAGE_VERSION=26.02.0.8
AUTOINSTALL="yes"
