;; * For SCIMAX starterkit, install scimax first.
(setq warning-minimum-level :emergency)
(setq package-enable-at-startup nil)

;; * Dynamic module dlopen on NixOS
;; Precompiled .so files from ELPA (jinx-mod.so, pdf-tools, vterm-module,
;; tree-sitter shared libs…) call dlopen() at module-load time and look
;; up libraries via LD_LIBRARY_PATH. nix-ld only intercepts execve, not
;; in-process dlopen, so we still need the path explicitly. Prepend the
;; system profile lib dir before anything that might (require 'jinx).
(let* ((sys-lib "/run/current-system/sw/lib")
       (existing (or (getenv "LD_LIBRARY_PATH") "")))
  (when (file-directory-p sys-lib)
    (unless (string-match-p (regexp-quote sys-lib) existing)
      (setenv "LD_LIBRARY_PATH"
              (if (string-empty-p existing)
                  sys-lib
                (concat sys-lib ":" existing))))))

;; * Tree-sitter grammar load path
;; Prebuilt grammar shared libs (libtree-sitter-magik.so, …-rust.so) live in
;; ~/Projects/emacs/tree-sitter/.  Emacs only auto-searches
;; <user-emacs-directory>/tree-sitter (i.e. ~/.emacs.d/tree-sitter/, which
;; doesn't exist here), so *-ts-mode can't find them unless we register our
;; own dir.  Without this, opening a .magik file warns that the magik grammar
;; is unavailable.
(when (and (fboundp 'treesit-available-p) (treesit-available-p))
  (require 'treesit)
  ;; Custom prebuilt grammars shipped with this config (magik, rust).
  (let ((ts-dir (expand-file-name "~/Projects/emacs/tree-sitter")))
    (when (file-directory-p ts-dir)
      (add-to-list 'treesit-extra-load-path ts-dir)))
  ;; Nix-built grammars (json/python/html/css/bash/…).  home-manager writes
  ;; the current store path into this generated file (see NixOS/home.nix).
  (let ((nix-ts (expand-file-name "~/.emacs.d/nix-tree-sitter.el")))
    (when (file-exists-p nix-ts)
      (load nix-ts nil t))))

;; Keep jinx-mod.so's rpath fresh across ELPA upgrades.
;; ELPA periodically replaces our patched jinx-mod.so with a fresh
;; prebuilt one that has no rpath; dlopen of libenchant-2.so.2 then
;; fails inside envrc/devenv buffers (where LD_LIBRARY_PATH is
;; replaced).  ~/.local/bin/jinx-rebuild-mod (generated by home.nix)
;; checks for our rpath marker and rebuilds the .so with it if
;; missing.  All nix-store paths are inlined at home-manager build
;; time, so it works regardless of how Emacs was launched.
(let ((rebuild (expand-file-name "~/.local/bin/jinx-rebuild-mod")))
  (when (file-executable-p rebuild)
    (call-process rebuild nil nil nil)))

;; * Scimax
(setq scimax-journal-root-dir "~/Projects/journal/"
      nb-notebook-directory "~/Projects/")
;; (add-hook 'org-mode-hook 'scimax-autoformat-mode)

;; * Prevent undo tree files from polluting your git repo
(setq undo-tree-history-directory-alist '(("." . "~/.emacs.d/undo")))
;; Put backup files neatly away
(let ((backup-dir "~/.emacs.d/backups")
      (auto-saves-dir "~/.emacs.d/auto-saves"))
  (dolist (dir (list backup-dir auto-saves-dir))
    (when (not (file-directory-p dir))
      (make-directory dir t)))
  (setq backup-directory-alist `(("." . ,backup-dir))
        auto-save-file-name-transforms `((".*" ,auto-saves-dir t))
        auto-save-list-file-prefix (concat auto-saves-dir ".saves-")
        tramp-backup-directory-alist `((".*" . ,backup-dir))
        tramp-auto-save-directory auto-saves-dir))

(setq backup-by-copying t    ; Don't delink hardlinks
      delete-old-versions t  ; Clean up the backups
      version-control t      ; Use version numbers on backups,
      kept-new-versions 5    ; keep some new versions
      kept-old-versions 2)   ; and some old ones, too


;; * Treat all themes as safe
(setq custom-safe-themes t) 
(setq scimax-theme nil)

(defun ensure-package (pkg)
  "Install PKG unless already installed."
  (unless (package-installed-p pkg)
    (package-install pkg)))

;; * Auto Install My Packages
(setq package-selected-packages
      '(material-theme
	gruvbox-theme
	doom-themes
	ef-themes
	pdf-tools
	async
        neotree
        all-the-icons
        rainbow-delimiters
        yaml-mode
        dockerfile-mode
        toml-mode
        json-mode
	prettier-js
	js2-refactor
	rjsx-mode
	tide
	web-mode
	emmet-mode
	rustic
	ox-rst
	alert
	org-fragtog
	ob-nix
	latex-preview-pane
	org-modern
	slime
	nix-mode
	geiser-mit
	pyvenv
	nov
	markdown-mode
	mixed-pitch
	smartparens
	spice-mode
	ob-spice
	saveplace-pdf-view
	rg
	ob-rust
	lua-mode
	direnv
	magik-mode
	treemacs
	airdermacs
        ;; org-pandoc-import
	))
(package-install-selected-packages)

;; * Pyvenv
;; envrc-global-mode (in language.el) sets up per-buffer PATH/VIRTUAL_ENV
;; from each project's .envrc, so we no longer hard-pin a single venv
;; here.  The previous activate'd ~/Projects/python/.devenv/state/venv/
;; which no longer exists.  Just load the package; activation happens
;; per-buffer via envrc.
(require 'pyvenv)

(setq global-jinx-mode nil)

;; * Claude
(use-package claude-code-ide
  :vc (:url "https://github.com/manzaltu/claude-code-ide.el" :rev :newest)
  :bind ("C-c C-'" . claude-code-ide-menu) ; Set your favorite keybinding
  :config
  (claude-code-ide-emacs-tools-setup)) ; Optionally enable Emacs MCP tools

;; * Aidermacs
(use-package aidermacs
  :bind (("C-c a" . aidermacs-transient-menu))
  :config
  (with-temp-buffer
    (when (file-readable-p "~/.config/secrets/claude-api-key")
      (insert-file-contents "~/.config/secrets/claude-api-key")
      (setenv "ANTHROPIC_API_KEY" (string-trim (buffer-string)))))
  :custom
  (aidermacs-default-chat-mode 'architect)
  (aidermacs-default-model"opus"))
(setq aider-program "~/.local/bin/aider")
